(function(b,a,c,d){c.swipebox=function(i,s){var q,m={useCSS:true,useSVG:false,initialIndexOnArray:0,hideCloseButtonOnMobile:false,hideBarsDelay:0,videoMaxWidth:1140,vimeoColor:"cccccc",download:"保存图片",lasttip:"已到最后一张",beforeOpen:null,afterOpen:null,afterClose:null,loopAtEnd:false,autoplayVideos:false},o=this,e=[],f,j=i.selector,r=c(j),p=navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(Android)|(PlayBook)|(BB10)|(BlackBerry)|(Opera Mini)|(IEMobile)|(webOS)|(MeeGo)/i),l=p!==null||a.createTouch!==d||("ontouchstart"in b)||("onmsgesturechange"in b)||navigator.msMaxTouchPoints,h=b.innerWidth?b.innerWidth:c(b).width(),k=b.innerHeight?b.innerHeight:c(b).height(),g=0,n='<div id="mask"></div><div id="swipebox-overlay"><div id="swipebox-container"><div id="swipebox-slider"></div><div id="swipebox-bottom-bar"><div id="swipebox-arrows"><a id="swipebox-prev"></a><a id="swipebox-next"></a></div></div><a id="swipebox-close"></a></div></div><div id="bottom_box"><a id="swipebox-download"></a><div id="pd_box">APP查看高清大图</div></div><div id="pd_overlay" class="pd_hide"><div id="pd_close"><div class="close"></div></div><div id="pd_img_box"><image src="https://m.woyaogexing.com/static/images/minipd.png" /><text>扫码下载APP查看高清大图</text></div></div>';o.settings={};c.swipebox.close=function(){q.closeSlide()};c.swipebox.extend=function(){return q};o.init=function(){o.settings=c.extend({},m,s);if(c.isArray(i)){e=i;q.target=c(b);q.init(o.settings.initialIndexOnArray)}else{c(a).on("click",j,function(v){if(v.target.parentNode.className==="slide current"){return false}
if(!c.isArray(i)){q.destroy();f=c(j);q.actions()}
e=[];var t,u,w;if(!w){u="data-rel";w=c(this).attr(u)}
if(!w){u="rel";w=c(this).attr(u)}
if(w&&w!==""&&w!=="nofollow"){f=r.filter("["+u+'="'+w+'"]')}else{f=c(j)}
f.each(function(){var y=null,x=null;if(c(this).attr("title")){y=c(this).attr("title")}
if(c(this).find("img")){x=c(this).find("img").attr("src")}
e.push({href:x,title:y})});t=f.index(c(this));v.preventDefault();v.stopPropagation();q.target=c(v.target);q.init(t)})}};q={init:function(t){if(o.settings.beforeOpen){o.settings.beforeOpen()}
this.target.trigger("swipebox-start");c.swipebox.isOpen=true;this.build();this.openSlide(t);this.openMedia(t);this.preloadMedia(t+1);this.preloadMedia(t-1);if(o.settings.afterOpen){o.settings.afterOpen()}
this.download(t)},download:function(t){o.settings.download=m.download;c("#swipebox-download").html(o.settings.download);if(e[t]!==d){src=e[t].href}
c("#swipebox-download").attr("href",src);c("#swipebox-download").attr("download","");var u="<img src="+src+' style="display:none;border:none">';c("#swipebox-download").append(u)},build:function(){var u=this,t;c("body").append(n);t=c("#swipebox-close").css("background-image");c("#swipebox-close").css({"background-image":t});c.each(e,function(){c("#swipebox-slider").append('<div class="slide"></div>')});u.setDim();u.actions();u.gesture()},setDim:function(){var v,t,u={};if("onorientationchange"in b){b.addEventListener("orientationchange",function(){if(b.orientation===0){v=h;t=k}else{if(b.orientation===90||b.orientation===-90){v=k;t=h}}},false)}else{v=b.innerWidth?b.innerWidth:c(b).width();t=b.innerHeight?b.innerHeight:c(b).height()}
u={width:v,height:t};c("#swipebox-overlay").css(u)},resize:function(){var t=this;c(b).resize(function(){t.setDim()}).resize()},supportTransition:function(){var u="transition WebkitTransition MozTransition OTransition msTransition KhtmlTransition".split(" "),t;for(t=0;t<u.length;t++){if(a.createElement("div").style[u[t]]!==d){return u[t]}}
return false},doCssTrans:function(){if(o.settings.useCSS&&this.supportTransition()){return true}},gesture:function(){var D=this,C,F,E,w,y,A,x=false,v=false,z=10,B=50,G={},t={},H=c("#swipebox-top-bar, #swipebox-bottom-bar"),u=c("#swipebox-slider");D.setTimeout();c("#swipebox-overlay").bind("touchstart",function(I){c(this).addClass("touching");C=c("#swipebox-slider .slide").index(c("#swipebox-slider .slide.current"));t=I.originalEvent.targetTouches[0];G.pageX=I.originalEvent.targetTouches[0].pageX;G.pageY=I.originalEvent.targetTouches[0].pageY;c("#swipebox-slider").css({"-webkit-transform":"translate3d("+g+"%, 0, 0)","transform":"translate3d("+g+"%, 0, 0)"});c(".touching").bind("touchmove",function(K){t=K.originalEvent.targetTouches[0];if(!v){y=E;E=t.pageY-G.pageY;if(Math.abs(E)>=B||x){var J=0.75-Math.abs(E)/u.height();u.css({"top":E+"px"});u.css({"opacity":J});x=true}}
w=F;F=t.pageX-G.pageX;A=F*100/h;if(!v&&!x&&Math.abs(F)>=z){c("#swipebox-slider").css({"-webkit-transition":"","transition":""});v=true}
if(v){if(0<F){if(0===C){c("#swipebox-overlay").addClass("leftSpringTouch")}else{c("#swipebox-overlay").removeClass("leftSpringTouch").removeClass("rightSpringTouch");c("#swipebox-slider").css({"-webkit-transform":"translate3d("+(g+A)+"%, 0, 0)","transform":"translate3d("+(g+A)+"%, 0, 0)"})}}else{if(0>F){if(e.length===C+1){c("#swipebox-overlay").addClass("rightSpringTouch")}else{c("#swipebox-overlay").removeClass("leftSpringTouch").removeClass("rightSpringTouch");c("#swipebox-slider").css({"-webkit-transform":"translate3d("+(g+A)+"%, 0, 0)","transform":"translate3d("+(g+A)+"%, 0, 0)"})}}}}});return false}).bind("touchend",function(I){c("#swipebox-slider").css({"-webkit-transition":"-webkit-transform 0.4s ease","transition":"transform 0.4s ease"});E=t.pageY-G.pageY;F=t.pageX-G.pageX;A=F*100/h;if(x){x=false;if(Math.abs(E)>=2*B&&Math.abs(E)>Math.abs(y)){var J=E>0?u.height():-u.height();u.animate({top:J+"px","opacity":0},300,function(){D.closeSlide()})}else{u.animate({top:0,"opacity":1},300)}}else{if(v){v=false;if(F>=z&&F>=w){D.getPrev()}else{if(F<=-z&&F<=w){D.getNext()}}}}
c("#swipebox-slider").css({"-webkit-transform":"translate3d("+g+"%, 0, 0)","transform":"translate3d("+g+"%, 0, 0)"});c("#swipebox-overlay").removeClass("leftSpringTouch").removeClass("rightSpringTouch");c(".touching").off("touchmove").removeClass("touching")})},setTimeout:function(){if(o.settings.hideBarsDelay>0){var t=this;t.clearTimeout();t.timeout=b.setTimeout(function(){t.hideBars()},o.settings.hideBarsDelay)}},clearTimeout:function(){b.clearTimeout(this.timeout);this.timeout=null},showBars:function(){},hideBars:function(){},animBars:function(){},actions:function(){var u=this,t="touchend click";if(e.length<2){}else{c("#swipebox-prev").bind(t,function(v){u.getPrev();u.setTimeout()});c("#swipebox-next").bind(t,function(v){u.getNext();u.setTimeout()})}
c("#swipebox-close").bind(t,function(){u.closeSlide()})
c("#pd_box").bind(t,function(){u.showOrHidePd()})
c("#pd_close").bind(t,function(){u.showOrHidePd()})},setSlide:function(v,t){t=t||false;var w=c("#swipebox-slider");g=-v*100;if(this.doCssTrans()){w.css({"-webkit-transform":"translate3d("+(-v*100)+"%, 0, 0)","transform":"translate3d("+(-v*100)+"%, 0, 0)"})}else{w.animate({left:(-v*100)+"%"})}
c("#swipebox-slider .slide").removeClass("current");c("#swipebox-slider .slide").eq(v).addClass("current");this.setTitle(v);this.download(v);if(t){w.fadeIn()}
c("#swipebox-prev, #swipebox-next").removeClass("disabled");c("#swipebox-tips").remove();if(v===0){c("#swipebox-prev").addClass("disabled")}else{if(v===e.length-1&&o.settings.loopAtEnd!==true){c("#swipebox-next").addClass("disabled");o.settings.download="下一组";c("body").append('<p id="swipebox-tips"></p>');c("#swipebox-tips").html(o.settings.lasttip);c("#swipebox-download").html(o.settings.download);c("#swipebox-download").removeAttr("download");var u=c(".pageBtn .y").attr("href");c("#swipebox-download").attr("href",u)}}},openSlide:function(t){c("html").addClass("swipebox-html");if(l){c("html").addClass("swipebox-touch");if(o.settings.hideCloseButtonOnMobile){c("html").addClass("swipebox-no-close-button")}}else{c("html").addClass("swipebox-no-touch")}
c(b).trigger("resize");this.setSlide(t,true)},preloadMedia:function(t){var u=this,v=null;if(e[t]!==d){v=e[t].href}
setTimeout(function(){u.openMedia(t)},1000)},openMedia:function(u){var v=this,w,t;if(e[u]!==d){w=e[u].href}
if(u<0||u>=e.length){return false}
t=c("#swipebox-slider .slide").eq(u);t.addClass("slide-loading");v.loadMedia(w,function(){t.removeClass("slide-loading");t.html(this)})},setTitle:function(t){var u=null;c("#swipebox-title").empty();if(e[t]!==d){u=e[t].title}
if(u){c("#swipebox-top-bar").show();c("#swipebox-title").append(u)}else{c("#swipebox-top-bar").hide()}},loadMedia:function(u,v){var t=c("<img>").on("load",function(w){v.call(t)});t.attr("src",u)},getNext:function(){var u=this,v,t=c("#swipebox-slider .slide").index(c("#swipebox-slider .slide.current"));if(t+1<e.length){t++;u.setSlide(t);u.preloadMedia(t+1)}else{if(o.settings.loopAtEnd===true){t=0;u.preloadMedia(t);u.setSlide(t);u.preloadMedia(t+1)}else{c("#swipebox-overlay").addClass("rightSpring");setTimeout(function(){c("#swipebox-overlay").removeClass("rightSpring")},500)}}},getPrev:function(){var t=c("#swipebox-slider .slide").index(c("#swipebox-slider .slide.current")),u;if(t>0){t--;this.setSlide(t);this.preloadMedia(t-1)}else{c("#swipebox-overlay").addClass("leftSpring");setTimeout(function(){c("#swipebox-overlay").removeClass("leftSpring")},500)}},closeSlide:function(){c("html").removeClass("swipebox-html");c("html").removeClass("swipebox-touch");c(b).trigger("resize");this.destroy()},destroy:function(){c(b).unbind("keyup");c("body").unbind("touchstart");c("body").unbind("touchmove");c("body").unbind("touchend");c("#swipebox-slider").unbind();c("#swipebox-overlay").remove();c("#mask").remove();c("#bottom_box").remove();c("#swipebox-tips").remove();if(!c.isArray(i)){i.removeData("_swipebox")}
if(this.target){this.target.trigger("swipebox-destroy")}
c.swipebox.isOpen=false;if(o.settings.afterClose){o.settings.afterClose()}},showOrHidePd:function(){$("#pd_overlay").toggleClass("pd_hide");}};o.init()};c.fn.swipebox=function(f){if(!c.data(this,"_swipebox")){var e=new c.swipebox(this,f);this.data("_swipebox",e)}
return this.data("_swipebox")}}(window,document,jQuery));$(document).ready(function(){$("#pd_content,#pd_close_content").click(function(){$("#pd_overlay_content").toggleClass("pd_hide");});});